version: '3'
services: 
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'nab_icommerce_rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5673:5672'
    networks:
      - main_network

  products_db:
    image: 'mongo:latest'
    container_name: 'nab_icommerce_products_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nab_icommerce
      MONGO_INITDB_ROOT_PASSWORD: SrHbgm2PbLDnXBNN
      MONGO_INITDB_DATABASE: nab_icommerce
      MONGO_PORT: 27017
    volumes:
      - ./init-db-products/:/docker-entrypoint-initdb.d/
    ports:
      - '27019:27017'
    networks:
      - products_network

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    image: 'nab_icommerce_products'
    container_name: 'nab_icommerce_products'
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file: ./products/.env
    environment:
      MONGO_URL: mongodb://products_db
      MONGO_USER: nab_icommerce
      MONGO_PASSWORD: SrHbgm2PbLDnXBNN
      MONGO_DB: nab_icommerce
      AMQP_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - products_db
      - rabbitmq
    networks:
      - products_network
      - main_network
    
  activities_db:
    image: 'mongo:latest'
    container_name: 'nab_icommerce_activities_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nab_icommerce
      MONGO_INITDB_ROOT_PASSWORD: SrHbgm2PbLDnXBNN
      MONGO_INITDB_DATABASE: nab_icommerce
    volumes:
      - ./init-db-activities/:/docker-entrypoint-initdb.d/
    ports:
      - '27020:27017'
    networks:
      - activities_network

  activities:
    build:
      context: ./user-activities
      dockerfile: Dockerfile
    image: 'nab_icommerce_activities'
    container_name: 'nab_icommerce_activities'
    ports:
      - 8081:8080
    restart: unless-stopped
    env_file: ./user-activities/.env
    environment:
      MONGO_URL: mongodb://activities_db
      MONGO_USER: nab_icommerce
      MONGO_PASSWORD: SrHbgm2PbLDnXBNN
      MONGO_DB: nab_icommerce
      AMQP_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - activities_db
      - rabbitmq
    networks:
      - activities_network
      - main_network


networks: 
  products_network:
    driver: bridge
  activities_network:
    driver: bridge
  main_network:
    driver: bridge

volumes:
  .:
  node_modules: