version: '3'
services: 
  products_db:
    image: 'postgres:latest'
    container_name: 'nab_icommerce_db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SrHbgm2PbLDnXBNN
      POSTGRES_DB: nab_icommerce
    ports:
      - '54320:5432'
    networks:
      - products_network

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    image: 'nab_icommerce_products'
    container_name: 'nab_icommerce_products'
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file: ./products/.env
    environment:
      PG_URL: products_db
      PG_USER: postgres
      PG_PASSWORD: SrHbgm2PbLDnXBNN
      PG_DATABASE: nab_icommerce
      PG_PORT: 5432
      DB_SYNC: 'true'
    depends_on:
      - products_db
    networks:
      - products_network


networks: 
  products_network:
    driver: bridge

volumes:
  .:
  node_modules: